yolo_model:

  config_file:
    name: yolo_traffic.cfg
  weight_file:
    name: yolo_traffic.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      -green
      -red
      -redgreen
      -greengreen
      -redorange
      -orange
